version: '3.4'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.0
    restart: on-failure:0
    ports:
     - 8080:8080
     - 50051:50051
    volumes:
     - weaviate_data:/data
    env_file:
     - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      ENABLE_MODULES: 'text2vec-openai,generative-openai'
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      CLUSTER_HOSTNAME: 'node1'

volumes:
  weaviate_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/lorenzo/dev/weaviate_k8s_demo/weaviate_data